---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# spacefinder

<!-- badges: start -->
<!-- badges: end -->

Spacefinder provides functionality to identify best performing minimum volume subspaces within the hyperparameter space.

## Installation

You can install the development version of spacefinder from [GitHub](https://github.com/) with:

``` r
# install.packages("pak")
pak::pak("NikoGerman/spacefinder")
```

## Example

```{r example}
library(spacefinder)

DT <- data.table::data.table(
      task = sample(c("T1", "T2", "T3"), 300, replace = TRUE),
      auc = sample(runif(30), 100, replace = TRUE),
      hp1 = rnorm(300),
      hp2 = rnorm(300),
      hp3 = rnorm(300),
      cat_hp = sample(c("A", "B"), 300, replace = TRUE)
    )

tsk <- as_task_subspace(DT, auc ~ (hp1 + hp2 + hp3) * cat_hp)

learner <- LearnerSubspaceBox$new(tsk)

# train with slack
learner$train(lambda = .05)
```

```{r summary}
summary(learner)
```

```{r autoplot}
ggplot2::autoplot(learner, wrap = TRUE)$A
```
```{r outliers}
outliers(learner)
```

